{% set data= load_setup_py_data() %}
package:
  name: ts-m2
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - run_mtm2 = lsst.ts.m2.csc:run_mtm2

test:
  requires:
    - ts-conda-build
    - ts-simactuators
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts-tcpip
    - ts-utils
    - ts-m2com
  source_files:
    - python
    - bin
    - tests
    - setup.cfg
    - pyproject.toml
  commands:
    - pytest

requirements:
  host:
    - python {{ python }}
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  build:
    - python {{ python }}
    - setuptools_scm
    - setuptools
    - ts-conda-build =0.3
  run:
    - python {{ python }}
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-idl
    - ts-simactuators
    - pandas
    - ts-tcpip
    - ts-utils
    - ts-m2com
