{% set data= load_setup_py_data() %}
package:
  name: ts-m2
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python -m pip install --no-deps --ignore-installed .
  script_env:
    - PATH
    - PYTHONPATH
    - LD_LIBRARY_PATH
    - OSPL_HOME
    - PYTHON_BUILD_VERSION
    - PYTHON_BUILD_LOCATION
    - TS_CONFIG_MTTCS_DIR
    - LSST_DDS_DOMAIN

test:
  requires:
    - ts-conda-build
    - pandas
    - ts-simactuators
    - ts-dds
    - ts-idl {{ idl_version }}
    - ts-salobj {{ salobj_version }}
    - ts_tcpip
  source_files:
    - python
    - bin.src
    - tests
    - schema
    - setup.cfg
  commands:
    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-simactuators
    - pandas
    - ts_tcpip
